name: 'Terraform PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan output'
author: 'Rob Burger'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan]'
    required: true
  commenter_input:
    description: 'The comment to post from a previous step output. This must be trimmed to at least 128 KiB. Required for non plan commenter types.'
    required: false
  commenter_plan_path:
    description: 'The tfplan file. Required if commenter input is not set for plan commenter types.'
    required: false
  comment_prepend:
    description: 'Comment body to include before the formatted output'
    required: false
    default: ''
  comment_append:
    description: 'Comment body to append after the formatted output'
    required: false
    default: ''
  summary_table:
    description: 'Include a summary table of resource changes above the plan (applies only to type plan and requires a plan file)'
    required: false
    default: 'false'
  commenter_exitcode:
    description: 'The exit code from a previous step output'
    required: true
  terraform_version:
    description: 'The version of terraform with which a plan was generated'
    required: false
    default: latest
  working-directory:
    description: 'Working directory for action'
    required: false
    default: "/"
  debug:
    description: 'Enable debug log output'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Build commenter docker image
      run: |
        cd ${{ github.action_path }}
        docker build --build-arg TERRAFORM_VERSION=${{ inputs.terraform_version }} -t commenter .
      shell: bash

    - name: Run commenter image (plan)
      if: ${{ inputs.commenter_type == 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        COMMENT_PREPEND: ${{ inputs.comment_prepend }}
        COMMENT_APPEND: ${{ inputs.comment_append }}
        COMMENTER_PLAN_FILE: ${{ inputs.commenter_plan_path }}
        SUMMARY_TABLE: ${{ inputs.summary_table }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
        COMMENTER_DEBUG: ${{ inputs.debug }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENT_PREPEND \
        -e COMMENT_APPEND \
        -e SUMMARY_TABLE \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        -e COMMENTER_PLAN_FILE \
        -e COMMENTER_POST_PLAN_OUTPUTS \
        -v "$(pwd)"/${{ inputs.working-directory }}:/workspace \
        commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}
      shell: bash

    - name: Run commenter image (non-plan)
      if: ${{ inputs.commenter_type != 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        COMMENT_PREPEND: ${{ inputs.comment_prepend }}
        COMMENT_APPEND: ${{ inputs.comment_append }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
        COMMENTER_DEBUG: ${{ inputs.debug }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENT_PREPEND \
        -e COMMENT_APPEND \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}
      shell: bash


